### ISSUE TITLE
how to call a route function from cli ? 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [adrianfalleiro/slim-cli-runner#6]
Hi I am using cli middleware which works fine but here i have a situation that need to call a route, can you help me how to do it ? 

Below function is called from route, so how can i call this from CLI ? 
```
public function do(Request $request, Response $response)
{
}
```

**Comment by zelding** [comment]
You should never call/trigger controllers from `cli`; that is why commands are not controllers.

If you want to do something in a command that a controller already does, then you should refactor the controller code in a way that the logic you want to use elsewhere too is available elsewhere too ^^

That is why Business-Logic and Services were invented/specified.

So, if you were gonna query some users, than create a UserService that will fetch users for you, and use that in the Controller and the Command too.

Otherwise, I think you might be able to use `\Slim\Http\Environment::mock()` to simulate a request, and with that invoke a specific controller; **but you should never do that**

**Comment by adrianfalleiro** [comment]
@ihatecodinglikeking As @zelding suggest, I would encourage you to structure your project in such a way that your business logic is contained in a service. 

Once you've registered your services with the Slim DI container, you can access it in both the route handler and the command handler.
